language: python
python:
  - "2.7"
  - "3.5"
addons:
  apt:
    packages:
    - python-numpy
    - python-scipy
    - libfftw3-dev
# command to install dependencies
install: "pip install astropy pyfftw"
# command to run tests
script: nosetests
